select distinct ?subject ?type ?predicate
	where {
		{
			?subject rdf:type owl:Class .
			?subject rdfs:subClassOf $parentNode$ .
			?subject rdf:type ?type .
			?subject ?predicate $parentNode$ .
		}
		UNION
		{
			?subject rdf:type owl:ObjectProperty .
			?subject rdfs:range $parentNode$ .
			?subject rdf:type ?type .
			?subject ?predicate $parentNode$ .
		}
		UNION
		{
			?subject rdf:type owl:ObjectProperty .
			?subject rdfs:domain $parentNode$ .
			?subject rdf:type ?type .
			?subject ?predicate $parentNode$ .
		}
		UNION
		{
			?subject rdf:type owl:DatatypeProperty .
			?subject rdfs:domain $parentNode$ .
			?subject rdf:type ?type .
			?subject ?predicate $parentNode$ .
		}
	}
order by ?subject
